### ISSUE TITLE
Adding more settings for file types

### ISSUE THREAD

**Issue by lithiumlab** [argnist/StaticSaver#1]
maybe:
<filename>.chunk.html
<filename>.template.html
<filename>.snippet.php
<filename>.plugin.php
just for adding some room for devs preferences.
haven't tried the plugin. its only a suggestion parting from the readme contents.

After few months from your last commit, do you still use it for your workflow?
Does it works ok in 2.2.7/2.2.8?

**Comment by argnist** [comment]
There are settings for extensions of every element's type. Yes, It works on 2.2.10.
