### ISSUE TITLE
Не получается настроить

### ISSUE THREAD

**Issue by sergant210** [argnist/StaticSaver#5]
Виталий, подскажите, в чем может быть проблема? 
Создаю сниппет. Настройки выполнил по видео. Но! 
1. источник файлов автоматом не устанавливается, приходится вручную выбирать.
2. Имя файла не формируется. Но если обновить страницу, то начинает работать правильно - появляется расширение php и имя формируется из названия сниппета.
3. static_default установлен в 1. Но галочка не ставится.
В журнале вижу только:
<b>Error caching lexicon topic lexicon/ru/staticsaver/default</b>

**Comment by argnist** [comment]
AjaxManager не стоит? С ним несовместимо.

**Comment by sergant210** [comment]
Да, установлен. Ясно. Спасибо
