### ISSUE TITLE
Unwanted prefix being added to file and category folder on creation

### ISSUE THREAD

**Issue by BearOutThere** [argnist/StaticSaver#6]
First of all thanks for the great plugin.  I like modx but not its insistence of storing code in the db.  Your plugin makes using IDE much easier.

Got a strange issue though.  upon creation of any element the type of element is being pre-fixed to the file name or category folder name.
For example creating a new chunk called 'test' results in the file called 'chunkstest.chk'
Creating a new chunk 'chunk1' in a category 'testcategory' results in 'chunkstestcategory/chunk1.chk'
It looks like lowcase name of the media source is being prepended.  I looked through the javascript file but couldn't find where that happens.
Any suggestions?

Also the staticsaver setting staticsaver.include_category is set to no but the category folder is still being created.

**Comment by argnist** [comment]
Can't reproduce issue with prefix. What other extras do you have?

**Comment by BearOutThere** [comment]
On 06/08/2014 03:24 PM, argnist wrote:

> Can't reproduce issue with prefix. What other extras do you have?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/argnist/StaticSaver/issues/6#issuecomment-45431360

It's a clean installation of Revo 2.2.4.  static saver is the only extra 
installed.
my skype is kiril.okun
if you want more real time info

**Comment by BearOutThere** [comment]
Just uninstalled and reinstalled the plugin.
The same thing happens.  chunkstestchunkc.chk

i installed modx from the develop branch of the git repository.
could it be that there were some new changes in 2.2.4?

**Comment by BearOutThere** [comment]
On 06/08/2014 03:24 PM, argnist wrote:

> Can't reproduce issue with prefix. What other extras do you have?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/argnist/StaticSaver/issues/6#issuecomment-45431360.

so i played more with it and realized that the media source folder is 
not being used.  creating a new chunk 'test' creates a file 
'chunkstest.chk' under 'elements' folder not in 'elements/chunks'. so it 
looks like somehow 'chunks' gets prepended to the file name rather than 
used as the folder name.

**Comment by BearOutThere** [comment]
On 06/08/2014 03:24 PM, argnist wrote:

> Can't reproduce issue with prefix. What other extras do you have?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/argnist/StaticSaver/issues/6#issuecomment-45431360.

Finally figured it out and what a simple boneheaded thing it was.  I 
left out the trailing '/' in the media source definition.
After adding it everything works fine.
Sorry about that.

One suggestion though.
It would be nice during an element renaming to either rename an old file 
or create new/delete old one.  Otherwise i can see orphaned files 
accumulating over time.
Thanks again for a great tool.
